<?xml version="1.0" encoding="utf-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" name="PTZService" targetNamespace="http://www.onvif.org/ver20/ptz/wsdl">
  <wsdl:import namespace="http://www.onvif.org/ver20/ptz/wsdl" location="../wsdl/ptz.wsdl"/>
  <wsdl:types>
    <xs:schema targetNamespace="http://versteege.com/rpos">
      <xs:import schemaLocation="../wsdl/ptz.wsdl" namespace="http://www.onvif.org/ver20/ptz/wsdl"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:service name="PTZService">
    <wsdl:port name="PTZ" binding="tdv:PTZBinding">
      <soap:address location="http://localhost:8000/onvif/ptz_service"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
